# Site settings
title: 生命不息，折腾不止
author: Quebradawill
author_avatar: /images/header.jpg
email: alias@domain.tld
description: 生命不息，折腾不止
url: "https://quebrada.github.io"
domain: "http://www.quebradawill.com"
github_username: quebrada
github_site_repo: quebrada/quebrada.github.io
disqus: Quebradawill


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
